### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by shanness** [caoli5288/java-decompiler-plugin-cfr#4]
Hi, I can't figure out how to get this to build the jar needed for installing a plugin.
The jar it generates in `out` doesn't have your classes or the plugin.xml in them, and it's not generating any class files for you two kotlin classes

I worked around it by creating my own plugin project, copying your two classes in and then adding them and your plugin.xml to the jar your project built.

**Comment by caoli5288** [comment]
See release plz.

**Comment by shanness** [comment]
Ahh, thanks, ooops.
